### ISSUE TITLE
Fix security vulnerability

### ISSUE THREAD

**Issue by AnBusse** [FrontEndFoxes/ff-web#1]
When cloning the repository and running `npm install`, you are being alerted to a security vulnerability:

![npm-vulnerability](https://user-images.githubusercontent.com/22819829/92154453-182d2080-ee26-11ea-9e19-636c61eb9cd3.JPG)

Fix it by updating the package.

**Comment by jlooper** [comment]
This one is a Vue issue, I believe, to be researched

**Comment by jlooper** [comment]
fixed with last push
