### ISSUE TITLE
Homepage photo tweak for layout and content

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#12]
- Make the bottom photo gallery show three different photos from our current gallery on frontendfoxes.org (you can recommend links here and I will approve). 
- Ensure that the three-card horizontal images scale for mobile to stack vertically on small screens
- Give the bottom photo gallery a margin to match the page/nav margins

**Comment by mariajcb** [comment]
Hey, Jen, I think I'll pick this one up.

**Comment by jlooper** [comment]
here are some pics we can use! 

<img width="739" alt="VV-Nigeria" src="https://user-images.githubusercontent.com/1450004/95128441-6ab07400-0727-11eb-9fae-4f07277a13bd.png">
![japan](https://user-images.githubusercontent.com/1450004/95129011-50c36100-0728-11eb-9129-47ce0baab8ba.jpg)

**Comment by jlooper** [comment]
![japan](https://user-images.githubusercontent.com/1450004/95129043-62a50400-0728-11eb-94ca-ad852037ca65.jpg)

**Comment by mariajcb** [comment]
Issue completed in [PR#35](https://github.com/FrontEndFoxes/ff-web/pull/35)
