### ISSUE TITLE
Complete Teams page migration

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#16]
hi, thank you for your work on this. It looked great to me on the Netlify site. Can you do this:

grab all the images from the current frontendfoxes.org site on the Team page and zip them and attach them to this issue. I will upload them to Cloudinary and complete the linking. For now, you can put a placeholder in the .json on the image path.

thanks!
Jen

**Comment by alxmcr** [comment]
Hi!

This file .zip has all leaders images (plus a fox-placeholder.jpg image)
[images-team-cloudinary.zip](https://github.com/FrontEndFoxes/ff-web/files/5319451/images-team-cloudinary.zip)

**Comment by jlooper** [comment]
Thank you! uploaded. I really appreciate your contribution!

**Comment by alxmcr** [comment]
> Thank you! uploaded. I really appreciate your contribution!

I'm so sorry, how should I update the image paths?

I have this image path (from original code):
[https://res.cloudinary.com/front-end-foxes/image/upload/v1601240911/ChapterLeaders/jen_looper_gpiyff.jpg](https://res.cloudinary.com/front-end-foxes/image/upload/v1601240911/ChapterLeaders/jen_looper_gpiyff.jpg) **It works** ✅.

But, I was trying to use names for _other images (from .zip file)_ unfortunately **they aren't working.** 

Please 🙏, is there a **base path**?

For example:
[https://res.cloudinary.com/front-end-foxes/image/upload](https://res.cloudinary.com/front-end-foxes/image/upload)

then add some **version or code**, **image folder**, and **image name**:
[https://res.cloudinary.com/front-end-foxes/image/upload/versionABC/ChapterLeaders/<image_name>](https://res.cloudinary.com/front-end-foxes/image/upload/versionABC/ChapterLeaders/<image_name>)

I'll appreciate your help! 🙂

**Comment by jlooper** [comment]
Hi, how about if I add the paths if you can just leave them blank for now. I have to copy/paste a little from Cloudinary 🙏

**Comment by alxmcr** [comment]
> Hi, how about if I add the paths if you can just leave them blank for now. I have to copy/paste a little from Cloudinary 🙏

Oh... I understand. No problem. I'm so sorry I didn't know. 
OK,  I'll leave them blank and commit my changes!

Thank you so much for your support! We did a good job! 🙂

**Comment by jlooper** [comment]
Alex I'd like to send you a little gift- can you email your shipping address to Jen @ frontendfoxes.org
