### ISSUE TITLE
Fixing the position of the sharing menu on midsize screens

### ISSUE THREAD

**Issue by AnBusse** [FrontEndFoxes/ff-web#2]
On medium-sized to large screens (breakpoints 768px and 1024px width), the sharing menu is not being displayed properly.

    Clone the repository, and run npm install and npm run serve
    Open the site in the browser
    Visit either the About, Team, or Gallery page

Expected behavior
breakpoint: 768px: align the share menu in the Header.vue so it is not partially obscured by the top menu anymore
breakpoint: 1024px: hide the share menu

![midsize-screen](https://user-images.githubusercontent.com/22819829/92324460-2a83a600-f042-11ea-810a-61875d73f8a9.JPG)
![big-screen](https://user-images.githubusercontent.com/22819829/92324461-2b1c3c80-f042-11ea-9297-9b0117b722f9.JPG)

**Comment by jlooper** [comment]
note - this is because these pages are not built out. The view you see is the bottom nav...so the thing to fix here is the mobile view for the bottom nav

**Comment by jlooper** [comment]
fixed
