### ISSUE TITLE
About us page tidy-up

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#38]
I think @mariajcb had ideas on tidying this page ♥️🦊♥️🦊

**Comment by BraydenTW** [comment]
@jlooper, do you mean just add some more spacing between the top and the bottom of the pages?

**Comment by jlooper** [comment]
Hi, I'll let @mariajcb drive this, I think she has ideas 😍

**Comment by BraydenTW** [comment]
Ok... no problem :D

**Comment by mariajcb** [comment]
@BraydenTW Thank you for jumping in - I wanted to do the following:
- make side margins match other pages
- add padding to top and bottom
- add design elements to break up the "block of text"

Do you have suggestions as to what design elements could be used here?  I was thinking of tweaking the headings and bringing out some blockquotes.

**Comment by mariajcb** [comment]
@jlooper what are the links for Patreon and Github sponsors?

**Comment by BraydenTW** [comment]
@mariajcb , sounds great! I’ll work on those changes today. However I have one question. 

> - add design elements to break up the "block of text"

Can you clarify? Do you mean adding a flexbox system/images in?

**Comment by mariajcb** [comment]
@BraydenTW - that's actually what I would need your input on as a designer.  Here is what I had in mind:
- Blockquote "We will admit any person who lives as a woman and consistently identifies as a woman. We also welcome those who were assigned female at birth and who feel they belong in our community of women. We seek to provide students with a uniquely empowering learning environment—one designed specifically to prepare women to thrive in a complex world."
-- perhaps something like the example under "hanging punctuation" in https://css-tricks.com/quoting-in-html-quotations-citations-and-blockquotes/, but with dark blue instead of pink
- Emojis or graphics
-- Ex: platinum/gold/silver sponsors
- Typography
-- "Sponsorship" could use some bolding, italics, or maybe even smaller headings to bring attention to different levels of support
- Other graphics or custom icons
- Play around with backgrounds
-- place some paragraphs in a dark blue box, see how that looks
-- be conscious of color contrast and accessibility

I think we have some room for creativity here!

**Comment by jlooper** [comment]
> @jlooper what are the links for Patreon and Github sponsors?

Patreon.com/vuevixens

GitHub.com/sponsors/FrontEndFoxes

**Comment by BraydenTW** [comment]
@mariajcb and @jlooper I’d be happy to take this on. I’ll do my best at bringing a modern and simplistic perspective to the about page.

**Comment by mariajcb** [comment]
@BraydenTW Cool! I was going to code the thing myself, but you're a better candidate for this issue, since I'm squarely on the developer side, rather than design. Let me know if you want to bounce ideas back and forth. :)

**Comment by BraydenTW** [comment]
@mariajcb sure! I’ll let you know :D

**Comment by jlooper** [comment]
Thanks folks! Maybe a quick mock-up in figma would work best before launching...I don't think we need anything too fancy here and I'd like to just use Tailwind for all css as that's been our stack 🤗🙏

**Comment by BraydenTW** [comment]
@mariajcb and @jlooper, I am not fluent in Tailwind so I think I’ll stick to creating the mockup and @mariajcb , do you think you could code it with Tailwind?

**Comment by jlooper** [comment]
if not I can tackle it :)

**Comment by BraydenTW** [comment]
@jlooper by all means. I’ll have the Figma file ready to display in the next few hours.

**Comment by mariajcb** [comment]
@BraydenTW Yeah, I'd be happy to!

**Comment by BraydenTW** [comment]
Sounds great!

**Comment by BraydenTW** [comment]
Hey @jlooper  and @mariajcb , here is the link to the Figma file redesign: https://www.figma.com/file/363E50VYt5uHkM1sIar2tO/Front-End-Foxes-About-Us-Page?node-id=0%3A1

Let me know if there is any other adjustments I can make.

**Comment by jlooper** [comment]
Very pretty! I think we need to use our color scheme (blue/orange/white) but it's a very nice start. WE can keep the gradient on this page; the graphics are quite nice though. A big 'how to sponsor' callout is a good idea.

I think if we can simplify it down to our base colors it will be really cool. One thing, we have to be careful of our translations of this page (so edits need to propagate to translations). 

Also let's try to build up our GitHub sponsor link! 

thanks for these nice ideas!

**Comment by BraydenTW** [comment]
You're welcome. Let me know if there are any further tasks I should complete. 

If not then I can hand it off to you to do the code 👍

**Comment by BraydenTW** [comment]
@mariajcb thanks! Yes, I will in the next hour. 

@jlooper I am not clear on a few things:

> Also let's try to build up our GitHub sponsor link!
>  One thing, we have to be careful of our translations of this page (so edits need to propagate to translations).

Thanks!

**Comment by jlooper** [comment]
hi, thanks everyone! to clarify:

Also let's try to build up our GitHub sponsor link!
- I'd like to add the GitHub Sponsor link as one more option for sponsorship (https://github.com/sponsors/FrontEndFoxes)
One thing, we have to be careful of our translations of this page (so edits need to propagate to translations).
- There was a lot of translation work done on this site, and it may be that the About page translation block has to be broken up into parts so that you can interleaf images. If that change is made, it needs to propagate to all our translations

**Comment by ariain** [comment]
Hi @mariajcb @jlooper, if this is not complete yet, I would like to give it a try...

**Comment by mariajcb** [comment]
@ariain thank you for your interest! I'm in the middle of working on it, though, and I'd like to see it through to the end.
