### ISSUE TITLE
Standardize button format on home page

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#39]
Unless my eyes are deceiving me (perhaps?) the buttons for 'Workshops' and 'Patreon' are different than the Events card buttons. Let's standardize those to look the same.

https://ff-next.netlify.app/

**Comment by mariajcb** [comment]
You're right, those buttons totally look different. Looks like we've got a person who's an actual designer on the About page, so I'll take this one!

**Comment by astnrgn** [comment]
Hey there, I can update the "Workshops" and "Patreon" buttons to match those below in Upcoming events for Hacktoberfest

(found this issue through http://issuehub.io/)

**Comment by jlooper** [comment]
Great! Have at it! 🦊❤️

**Comment by astnrgn** [comment]
PR opened [here](https://github.com/FrontEndFoxes/ff-web/pull/42)

**Comment by jlooper** [comment]
awesome! Merged!

**Comment by jlooper** [comment]
@astnrgn happy to send you a little care package if you send me your mailing address - jen @ frontendfoxes.org
