### ISSUE TITLE
Put a little loader on images in cards

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#40]
A little loader will make the experience better as the images come from Cloudinary.

**Comment by Usateid** [comment]
May I ask you what part of the project should be involved ?

**Comment by jlooper** [comment]
Any inner page where there are images but especially Team and Gallery

**Comment by franciscoemanuel** [comment]
Hey @jlooper, I've created a PR (#50) for this issue. Waiting for your review 😄.
