### ISSUE TITLE
on iPad, Team cards are being cut off

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#46]
Probably we need to scale the cards less severely on iPad, make them more responsive.

**Comment by ariain** [comment]
@jlooper I would like to work on this...

**Comment by jlooper** [comment]
Awesome!

**Comment by ariain** [comment]
@jlooper can you give me some details like I know the website link is being cut-off, what else should I look for here??

**Comment by jlooper** [comment]
Right now there are two link options: twitter and web site. We need to make sure those are both visible on iPad; I'm guessing it's because we have a min-height forced on these cards

**Comment by ariain** [comment]
@jlooper will this be fine??
<img width="748" alt="Screenshot 2020-10-20 at 12 05 31 AM" src="https://user-images.githubusercontent.com/34205918/96497252-0aade780-1268-11eb-89e3-354aea644be6.png">
