### ISSUE TITLE
The home page cards don't scale easily if there are more than four or fewer than a multiple of four

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#48]
I love the cards when there are 4, but the way the card gallery on the home page is set up, they don't respond well if there are, for example, five or 6. Let's make them scale in batches of 3 if there are more than 4 cards.

**Comment by ariain** [comment]
@jlooper can I work on this??

**Comment by jlooper** [comment]
Sure!

**Comment by ariain** [comment]
@jlooper can you clarify one thing that I have to only scale these cards when events are more than 4

<img width="1792" alt="Screenshot 2020-10-18 at 11 28 45 PM" src="https://user-images.githubusercontent.com/34205918/96376059-6ca01b80-119a-11eb-886d-0986a4d7daf1.png">

in case if they are less than or equal to 4 then 4 cards on the screen...

Also this is for only desktop screen, not for iPad or iPhone...
Thanks..

**Comment by jlooper** [comment]
Basically the cards don't wrap nicely as is. If there are 6 for example they start a row at 4 at one width and then the second rows 2 cards are shown at a wider width. I think we are forcing the width to be too narrow. 6 cards should show a 3x2 grid honestly. In addition it would be great to only show cards marked 'live' in the json file without having gaps in the row - thanks!

**Comment by jlooper** [comment]
iPhone looks good, all cards are equal full-screen. I'll check iPad

**Comment by ariain** [comment]
@jlooper raised the pull request...
