### ISSUE TITLE
Gallery page

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#5]
Build a gallery page. It can be simpler than what is on frontendfoxes.org but should be organized by year. We can consider hosting images in a CDN on Cloudinary (ask Jen for info)

We can show one image for each event.

**Comment by CodeSadhu** [comment]
@jlooper I'll have to learn Vue first. But would definitely love to contribute!

**Comment by jlooper** [comment]
Thank you @CodeSadhu!

**Comment by alxmcr** [comment]
Hi!

Today, I was working with this issue, and I've deployed the code on Netlify **[here](https://frontendfoxes-gallery-review.netlify.app/)**. Could you please **review** this website? 🙏🙏 I'll appreciate your **feedback** or any **recommendation**! because I don't know if **the result is as expected** 😊.

Also, I've **downloaded images** from frontendfoxes.org (and compressed in a .zip file), I'm not sure 😔 ... maybe, they need to be uploaded to Cloudinary  🙂.

[images-gallery-cloudinary.zip](https://github.com/FrontEndFoxes/ff-web/files/5322764/images-gallery-cloudinary.zip)

**Comment by jlooper** [comment]
hi @alxmcr! Wow, thank you for tackling this. I think this is a great start! I wonder if we can change the card format a bit. If you look at our previous events cards, maybe we can emulate that https://web.archive.org/web/20200115200023if_/https://www.vuevixens.org/

I think we can remove the emoji :)

The code should still be in the /website repo on this account, on the homepage.

Then, we need to find a way to show the actual gallery image. Maybe a modal? 

The alternative, which I was thinking would work best, would be to just have the cards with one image from each skulk showing, in which case we need bigger cards. Then, all the images are on the page without anyone needing to click.

Which do you think will work better? The goal of this page is to show all our happy events.

**Comment by alxmcr** [comment]
> hi @alxmcr! Wow, thank you for tackling this. I think this is a great start! I wonder if we can change the card format a bit. If you look at our previous events cards, maybe we can emulate that https://web.archive.org/web/20200115200023if_/https://www.vuevixens.org/
> 
> I think we can remove the emoji :)
> 
> The code should still be in the /website repo on this account, on the homepage.
> 
> Then, we need to find a way to show the actual gallery image. Maybe a modal?
> 
> The alternative, which I was thinking would work best, would be to just have the cards with one image from each skulk showing, in which case we need bigger cards. Then, all the images are on the page without anyone needing to click.
> 
> Which do you think will work better? The goal of this page is to show all our happy events.

Hi!

I'm so sorry for my delay with the response 😔😔  . Thank you for your recommendations and feedback!

- OK, I'll remove the emoji 👍 .
- About the cards, I'll check and fix them. Thanks!
- Happy event gallery with your image gallery 😄 -> I worked with some [ideas](https://www.figma.com/file/WCNQgCY7AhEsHzbiVDucXP/jen-send?node-id=0%3A1) on Figma.


I'm sorry they're not professional designs (only crazy **ideas** or drawings) I hope they are useful for you 🙏🤞.

All ideas are only ideas, I've never built them before, but I think they would be **a big challenge** for me (all of them) and I would like to work them 😄.

Could you please give me your opinion or comments about the **ideas or little designs**? 🙏 I'll appreciate it. I believe the ideas could be **improved** or there are **better ideas** or **a mix of them**. It's very important to me.

Thanks for your time and support!

**Comment by jlooper** [comment]
Thank you so much for your amazing contributions. I realize that I have neglected this area of our old web site, and it's pretty badly broken so I have work to do to get a good selection of our gallery images into Cloudinary.

Anyway, I love your work on Figma. I like your ideas a lot. Based on the Figma ideas, I feel like maybe we can modify Idea 5 to work nicely for us. Let's do this:

a set of breadcrumb links at the top with the dates

and when you click a date, the cards refresh to show just one image per meetup. We can get rid of the city images and just add a place holder for now of a meetup (I'll go find the images to use). Then we don't have to do any fancy modals or effects on the image. We can just show the nice image of a meetup with the city underneath. The point of this page is to show how many events we have done all over the world, but just one meetup image per card, with no popup or overlying text, will do the job.

Hope this makes sense?

Thank you again so much for your valuable contributions!!

**Comment by alxmcr** [comment]
> Thank you so much for your amazing contributions. I realize that I have neglected this area of our old web site, and it's pretty badly broken so I have work to do to get a good selection of our gallery images into Cloudinary.
> 
> Anyway, I love your work on Figma. I like your ideas a lot. Based on the Figma ideas, I feel like maybe we can modify Idea 5 to work nicely for us. Let's do this:
> 
> a set of breadcrumb links at the top with the dates
> 
> and when you click a date, the cards refresh to show just one image per meetup. We can get rid of the city images and just add a place holder for now of a meetup (I'll go find the images to use). Then we don't have to do any fancy modals or effects on the image. We can just show the nice image of a meetup with the city underneath. The point of this page is to show how many events we have done all over the world, but just one meetup image per card, with no popup or overlying text, will do the job.
> 
> Hope this makes sense?
> 
> Thank you again so much for your valuable contributions!!

Thanks for your words 😊! I appreciate them a lot. They're very important to me!

I modified the idea 5, and I designed [two alternatives](https://www.figma.com/file/tOSlvTo1lMkZahPjMypwlE/idea-5-modified?node-id=0%3A1):

- Gallery (with repeated dates)
- Gallery (without repeated dates)

What do you think about them? **Is it expected?** 

Please, let me know it 🙏. I'll consider all your advice!
Thanks!

**Comment by jlooper** [comment]
hi, how about this: for dates, we just sort by year (2018 - 2019 - 2020) - I will work on finding examples to populate the views. Then, we can just show cards for all 2018 meetups, all 2019 meetups, etc. grouped per page. Is that ok?

**Comment by alxmcr** [comment]
> hi, how about this: for dates, we just sort by year (2018 - 2019 - 2020) - I will work on finding examples to populate the views. Then, we can just show cards for all 2018 meetups, all 2019 meetups, etc. grouped per page. Is that ok?

Hi!

I was confused. I'm sorry. Well, today, I was working with the gallery and this is a [new version](https://ff-gallery-v2.netlify.app/) 😄. I hope it is as expected or I'm open completely to new improvements or recommendations. Could you please review it? I'll appreciate it 🙏. 

Thanks for your time and support!

**Comment by jlooper** [comment]
This is perfect!! If you can just give a little border around the cards to match the team cards it will be just right. I'm guessing there's a JSON file behind it, like for other pages? 

Awesome!

**Comment by alxmcr** [comment]
> This is perfect!! If you can just give a little border around the cards to match the team cards it will be just right. I'm guessing there's a JSON file behind it, like for other pages?
> 
> Awesome!

Thanks!

Great! I fixed the card's border. This is a [new version](https://ff-gallery-v3.netlify.app/). Could you please review it? I'll appreciate it 🙏. Before we have a happy work finished😊.

- Yes, I created a file: 'events-gallery.json', and get years from events and filter them by year.

Thanks for your support, time, and opportunity! I learned a lot😄


[json_events-gallery.zip](https://github.com/FrontEndFoxes/ff-web/files/5335069/json_events-gallery.zip)

**Comment by jlooper** [comment]
I love it. If you ship the code I'll populate the cards!

And please email me at jen @ frontendfoxes.org so I can send you a package!

**Comment by jlooper** [comment]
Amazing contribution! Thank you!

**Comment by alxmcr** [comment]
> I love it. If you ship the code I'll populate the cards!
> 
> And please email me at jen @ frontendfoxes.org so I can send you a package!

Wow! Thank you so much! You're a kind person. It's a big surprise! I'll write to your email. Thanks!
