### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#6]
Create a new Team page, based on the look of the old one on frontendfoxes.org. Build it according to the Sponsors pattern, with a flat .json file behind it.

**Comment by jlooper** [comment]
The basic buildout is done, we just need to populate it. The images can be kept in Cloudinary.

**Comment by jlooper** [comment]
https://www.frontendfoxes.org/team - full migration needed 😍😍😍

**Comment by alxmcr** [comment]
Hi!

It's possible that please, share with us the images paths in **Cloudinary**. In https://www.frontendfoxes.org/team, some images paths aren't in Cloudinary. 

Please, I'll appreciate it!

**Comment by jlooper** [comment]
here we go! https://github.com/FrontEndFoxes/ff-web/issues/16
