### ISSUE TITLE
Sponsors page

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#7]
Transfer all information on sponsors from frontendfoxes.org, including logos.

**Comment by apdsrocha** [comment]
Hi @jlooper! I would love to try my hand at this task :)

**Comment by jlooper** [comment]
Go for it! I've been putting images on Cloudinary

**Comment by apdsrocha** [comment]
Cool, thank you for the tip! I wasn't familiar with Cloudinary, should I just set up an account and host images there?

**Comment by jlooper** [comment]
Hi, I have an account for the organization. Perhaps you can zip the images for me and I will upload them, and link the paths to the json. I started this process for the Teams page, as a reference. Thank you!!

**Comment by apdsrocha** [comment]
Perfect, will do! Thank you so much!

**Comment by jlooper** [comment]
Thank you for your contribution! Please feel free to email me at jen @ frontendfoxes.org and I'll send you a little token of our esteem!
