### ISSUE TITLE
Homepage: Events

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#8]
Redesign the Events area to make it pop. This is the most important part of the web site so I'm open to suggestions

**Comment by rsales** [comment]
Hi @jlooper, I would love to be able to work on the development of this feature implementation in homepage.

I will be very happy if I can contribute to the project **Front-End Foxes**

**Comment by jlooper** [comment]
Happy for your contribution! PR away! 😍

**Comment by rsales** [comment]
Hi @jlooper, Follow my proposal for the design of the home page together with the events section 🙂

**Desktop:** https://www.figma.com/file/9i6C5r11tOwKFiuMBLc9wJ/ff-web?node-id=2%3A6
**Mobile:** https://www.figma.com/file/9i6C5r11tOwKFiuMBLc9wJ/ff-web?node-id=4%3A619

**Comment by jlooper** [comment]
hi, this is a great start! thank you!

Here are my thoughts:

- let's concentrate for now on the card implementation for events. I think they look great as you designed them; let's display them as a grid, maybe 4 across, so that we can showcase as many events on the homepage as possible. 

I think we don't need to add the people graphics, and let's keep the top logo with the important text as is with the orange buttons. Maybe we can keep that orange button design from the current top area consistent in the event cards. 

Looking nice!! thank you!

**Comment by alxmcr** [comment]
Hi!

I don't know if someone is still working or need help with this issue, but I would like to help with the solution. 

In any case, I was working with [some ideas](https://www.figma.com/file/cBe9Bc3FWWx8hfgvzDzfMz/Events-Page?node-id=0%3A1), maybe they could help us 😄. Could you please review them? I'll appreciate it. Please, let me know your opinions or comments.

Have a nice day. Thanks!

**Comment by rsales** [comment]
Hi @alxmcr, I already started developing the card component. Yes man we can exchange an idea about the implementation of the cards.

**Comment by alxmcr** [comment]
> Hi @alxmcr, I already started developing the card component. Yes man we can exchange an idea about the implementation of the cards.

Great @rsales! Of course, a few days ago I created a component (**EventCard**) component, maybe It can help you with work! 👍

**Comment by jlooper** [comment]
@rsales thank you so much for this contribution! Can you email me at jen @ frontendfoxes.org and I'll send you a small token of our appreciation? 🦊♥️
